services:
  app:
    image: openjdk:21
    container_name: kotlin-spring-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - localstack
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "local"
      AWS_ACCESS_KEY_ID: "aws_access_key"
      AWS_SECRET_ACCESS_KEY: "aws_secret_key"
      AWS_REGION: "us-east-1"
      DYNAMODB_ENDPOINT: "http://localstack:4566"
      SQS_ENDPOINT: "http://localstack:4566"

  localstack:
    image: localstack/localstack:2.2
    container_name: localstack
    environment:
      SERVICES: "dynamodb,sqs"
      AWS_ACCESS_KEY_ID: "aws_access_key"
      AWS_SECRET_ACCESS_KEY: "aws_secret_key"
      DEFAULT_REGION: "us-east-1"
    ports:
      - "4566:4566"
    volumes:
      - ./init-scripts:/etc/localstack/init/ready.d
